# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 81fb422a52e7d05974db582784277bba137f554b864550e6302cadaa124086c5a12fceaae5ade1ac5a6dee72bf3fd80af263827440be38fa83338375bdc85d1b

test:
  secret_key_base: f1f2d8bed77414c1b07503fff664a2d5d18f5acd56bea10f5b8a3384a926b1d8d3be7001fdfb8ace24bb498ab00f4743c1f9dccfa1fb61e929d503ceea802ab1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
